version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    container_name: go_dj_server
    command: /bin/sh -c "cd /app && go mod tidy && go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    depends_on:
      - 'mysql'
      - 'redis'
  fuzai:
    build:
      context: .
      dockerfile: DockerFile
    container_name: go_dj_server_1
    command: /bin/sh -c "cd /app && go mod tidy && go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "8887:8888"

  nginx:
    image: nginx:1.19-alpine
    container_name: go_dj_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "backend"

  mysql:
    image: mysql:8.0
    container_name: go_dj_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go
      MYSQL_USER: homestead
      MYSQL_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: go_dj_redis
    restart: always
    volumes:
      - redisdb:/data
    ports:
      - "6379:6379"

volumes:
  redisdb:
  mysqldb: