server:
  port: :8888
  env: dev

mysql:
  #host: go_dj_mysql
  host: 127.0.0.1
  port: 3306
  db: go
  user: homestead
  #password: 123456
  password: secret

redis:
  #host: go_dj_redis
  host: 127.0.0.1
  port: 6379
  auth:
  db: 0

log:
  level: info # 日志等级
  root_dir: ./storage/logs # 日志根目录
  filename: go_dj # 日志文件名称
  format: # 写入格式 可选json
  show_line: true # 是否显示调用行
  max_backups: 7 # 旧文件的最大个数
  max_size: 500 # 日志文件最大大小（MB）
  max_age: 28 # 旧文件的最大保留天数
  compress: true # 是否压缩

mail:
  host: smtp.163.com
  port: 25
  from: 18910856145@163.com
  secret:
  nickname: go-yangchunping
